import { Config } from "./config";
import { Meter as IMeter, MeterOptions, TracerOptions, Tracer } from "@opentelemetry/api";
export declare const track: (newConfig?: Partial<Config> | undefined) => void;
export declare const info: (message: string, attributes?: Record<string, any>) => void;
export declare const warn: (message: string, attributes?: Record<string, any>) => void;
export declare const debug: (message: string, attributes?: Record<string, any>) => void;
export declare const error: (message: string, attributes?: Record<string, any>) => void;
export declare const errorRecord: (e: Error) => void;
export declare const setAttribute: (name: string, value: any) => void;
export declare const getMeter: (name: string, version?: string, options?: MeterOptions) => IMeter;
export declare const getTracer: (name: string, version?: string, options?: TracerOptions) => Tracer;
